### ISSUE TITLE
Datei gw-select liegt im falschen Repo

### ISSUE THREAD

**Issue by ghost** [FreiFunkMuenster/media-ffms#15]
Guten Morgen liebe FreifunkerInnen,

Ich bin mir sicher, dass diese [Datei](https://github.com/FreiFunkMuenster/media-ffms/tree/master/tools/gw-select) eher in das Repository [site-ffms](https://github.com/FreiFunkMuenster/site-ffms) gehört. Mir erschießt sich nicht, warum es in media-ffms liegen sollte.

Grüße,
brokenbike

**Comment by MPW1412** [comment]
In site-ffms liegen ausschließlich die Dateien, die zum Bauen der Firmware benötigt werden. Das Skript ist ein Werkzeug später die Auswahl eines Gateways zu erzwingen. Mit Firmware bauen hat das nichts zu tun.

Grüße
Matthias

**Comment by ghost** [comment]
Du bist allerdings immer noch nicht auf den Hinweis eingegangen, dass die Datei nicht in das Erschließungsprofil dieses Repositoriums passt. Wie stehst du dazu?

**Comment by MPW1412** [comment]
Hm, du meinst, weil es keine Mediendatei ist? Bisher war das Skript im Wiki, aber das ist FanLin wohl zu umständlich gewesen.

Du hast recht, dass es die einzige technische Datei ist, ich finde trotzdem, dass dieses Repo das ist, wo es am Besten reinpasst.

**Comment by elberfeld** [comment]
Ich habe dafür mal ein neues Repo erstellt : https://github.com/FreiFunkMuenster/tools
Hier gehört das definitiv nicht hin.

**Comment by ghost** [comment]
Vielen Dank! Das wollte ich auch vorstellen.

Am 08.10.2015 17:53 schrieb Christian Elberfeld:

**Comment by MPW1412** [comment]
Ich habe das Skript nun dorthin verschoben.
