### ISSUE TITLE
Lizenz?

### ISSUE THREAD

**Issue by andi98** [FreiFunkMuenster/media-ffms#16]
Hey,
unter welcher Lizenz steht der Kram in dieser Repo? Konkret geht es mir um das PDF "Rechtliche Infos", das ich gerne an unsere Community anpassen würde (Düren).
Schöne Grüße,
Andi

**Comment by kgbvax** [comment]
Generell CC. Have fun

**Comment by andi98** [comment]
Thx!

**Comment by kgbvax** [comment]
Gerade definiert als CC BY SA 4.0 :-)
